return {
	require("plugins.ui.blink-indent"),
	require("plugins.ui.bufferline"),
	require("plugins.ui.highlights"),
	require("plugins.ui.icons"),
	require("plugins.ui.mini-starter"),
	require("plugins.ui.neo-tree"),
	require("plugins.ui.notify"),
	require("plugins.ui.oil"),
	require("plugins.ui.pick"),
	require("plugins.ui.statusline"),
	require("plugins.ui.telescope"),
	require("plugins.ui.theme"),
	require("plugins.ui.which-key"),
	require("plugins.ui.workspaces"),
}
